# FUNDING.yml

github: [mdsbest]

custom: [
"https://getlooma.com/",
"https://serpdownloaders.github.io/tools/loom-video-downloader/",
"https://downloadingfreevideo.com/how-to-download-loom-videos",
"https://serp.co/products/loom-video-downloader/reviews/",
]
