# FUNDING.yml

github: [mdsbest]

custom: [
"https://getlooma.com/",
"https://serpdownloaders.github.io/",
"https://downloadingfreevideo.com/",
"https://serp.co/",
"https://serp.ai/",
"https://test1.com/",
"https://serp.com/",
"https://serp.best/",
]
