github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://getlooma.com/",
"https://serpdownloaders.github.io/tools/loom-video-downloader/",
"https://apps.serp.co/loom-video-downloader/",
"https://store.serp.co/product-details/product/loom-video-downloader",
"https://downloadingfreevideo.com/how-to-download-loom-videos",
"https://serp.co/products/loom-video-downloader/reviews/",
]
